# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
language: r
dist: bionic
jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
cache: packages

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages:
      - gcc-8
      - g++-8
      - gfortran-8

env:
  global:
  - MAKEFLAGS="-j 2"
  - COMPILER=g++-8
  - CC=gcc-8
  - CXX=g++-8
  - LINTR_COMMENT_BOT=false

r_packages:
  - deSolve
  - doMC
  - knitr
  - tidyr

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

before_install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:cran/imagemagick-dev
  - sudo apt-get install -y libmagick++-dev

script:
  - travis_wait 30 R CMD build .
  - travis_wait 120 R CMD check *tar.gz

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then Rscript -e "lintr::lint_package()"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "devel" ]; then travis_wait 120 Rscript -e 'covr::codecov()'; fi

