# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
language: r
dist: bionic
jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
cache: packages

 # GCC 6
    - compiler: gcc
      env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
            - libboost-regex1.55-dev
            - libboost-log1.55-dev
            - ninja-build

r_packages:
  - deSolve
  - doMC
  - knitr
  - tidyr

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

before_install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get install -y libmagick++-dev

script:
  - travis_wait 30 R CMD build .
  - travis_wait 100 R CMD check *tar.gz

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then Rscript -e "lintr::lint_package()"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "devel" ]; then travis_wait 40 Rscript -e 'covr::codecov()'; fi

